require "extensions/aws/ec2/instance"
require "extensions/aws/ec2/instance_collection"
require "extensions/bson/timestamp"
require "extensions/mongo/mongo_client"
require "extensions/mongo/mongo_replica_set_client"
